In [2]:
import numpy as np

# Basic Array Creation

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
lists= [1,2.5,"sai",True]
lists

[1, 2.5, 'sai', True]

In [9]:
# If list is pass in array then the higher priority variable will be apply to others..
arr2=np.array(lists)
arr2

array(['1', '2.5', 'sai', 'True'], dtype='<U32')

In [12]:
# Can print like 1-D 
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
# Can print like 2-D
# arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4=np.array(l)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [16]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [17]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [28]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [29]:
arr=np.arange(5,0,-2)
arr

array([5, 3, 1])

In [26]:
arr=np.arange(-1,-10)
arr

array([], dtype=int64)

In [25]:
arr=np.arange(-1,-10,-1)
arr

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])