In [3]:
import numpy as np

# Basic Array Creation

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [16]:
lists= [1,2.5,"sai",True]
lists

[1, 2.5, 'sai', True]

In [17]:
# If list is pass in array then the higher priority variable will be apply to others..
# If output is in [] single open and close bracket then it is vector 
# array(['1', '2.5', 'sai', 'True'], dtype='<U32')
arr2=np.array(lists)
arr2

array(['1', '2.5', 'sai', 'True'], dtype='<U32')

In [19]:
# Can print like 1-D 
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
# Can print like 2-D
# If output is in [[]] double or more open and close bracket then it is matrix 
# aarray([[1, 2, 3],
#      [4, 5, 6],
#      [7, 8, 9]])

# arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4=np.array(l)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [16]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [17]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [28]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [29]:
arr=np.arange(5,0,-2)
arr

array([5, 3, 1])

In [26]:
arr=np.arange(-1,-10)
arr

array([], dtype=int64)

In [25]:
arr=np.arange(-1,-10,-1)
arr

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

Other Array Generation Functions

In [7]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [9]:
arr=np.zeros((6,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr=np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
arr=np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# Random Generation Function

In [21]:
# default it is between 0 to 1 and this is called as normalization [rand]
np.random.rand(5)

array([0.79192127, 0.5512497 , 0.94731448, 0.48908617, 0.36111377])

In [22]:
# it is between 3 to -3 and this is called as standization [randn]
np.random.randn(5)

array([-1.27893705, -0.6109559 , -0.37028348, -2.17802584,  0.85845739])

In [23]:
np.random.randint(6)

2

In [26]:
np.random.randint(10,20,5)

array([12, 15, 19, 16, 13], dtype=int32)

# Array Attributes

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr.shape

(4, 3)

In [9]:
arr.size

12

In [10]:
arr.dtype

dtype('int64')

# Array Methods

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr.min()

np.int64(1)

In [14]:
arr.max()

np.int64(12)

In [15]:
arr.sum()

np.int64(78)

In [21]:
np.sum(arr,axis=0) # 0 for column 

array([22, 26, 30])

In [22]:
np.sum(arr,1) # 1 for rows

array([ 6, 15, 24, 33])

In [24]:
arr.mean() 

np.float64(6.5)

In [5]:
arr.std()

np.float64(3.452052529534663)

In [6]:
arr.argmax()

np.int64(11)

In [7]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [10]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
arr.reshape(6,5) # Reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr=arr.reshape(6,5) # Resize
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Numpy Indexing And Slicing Of Matrix

In [17]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
arr[0]

np.int64(11)

In [19]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [23]:
arr[-1:-5:-1]

array([20, 19, 18, 17])

In [24]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[0]

array([1, 2, 3, 4, 5])

In [26]:
arr[0,2]

np.int64(3)

In [27]:
arr[2,2]

np.int64(13)

In [30]:
arr[0:,2]

array([ 3,  8, 13, 18, 23, 28])

In [31]:
arr[1:3,3]

array([ 9, 14])

In [32]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

# Boolean Indexing

In [33]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
bool_index=arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [38]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array Operations